default_config:
logger:
  default: error
  logs:
    custom_components.tasmota_switch: debug


# tasmota_switch:
#   - url: 192.168.10.21
#     name: My Tasmota Plug
#   - url: 192.168.10.24